export const MENU_ITEM_LIST_REQUEST = 'MENU_ITEM_LIST_REQUEST'
export const MENU_ITEM_LIST_SUCCESS = 'MENU_ITEM_LIST_SUCCESS'
export const MENU_ITEM_LIST_FAIL = 'MENU_ITEM_LIST_FAIL'

export const MENU_ITEM_DETAILS_REQUEST = 'MENU_ITEM_DETAILS_REQUEST'
export const MENU_ITEM_DETAILS_SUCCESS = 'MENU_ITEM_DETAILS_SUCCESS'
export const MENU_ITEM_DETAILS_FAIL = 'MENU_ITEM_DETAILS_FAIL'
